version: "3.8"
services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: secret
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    ports:
      - "3306:3306"
    volumes:
      - ./oauth_server/src/main/resources/query.sql:/docker-entrypoint-initdb.d/query.sql
      - db:/var/lib/mysql
    networks:
      - bridge

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      PMA_HOST: mariadb
    ports:
      - "3307:80"
    networks:
      - bridge

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "3308:8080"
    environment:
      KC_DB: mariadb
      KC_DB_URL: jdbc:mariadb://172.17.0.1:3306/oauth
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: secret

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: secret
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - bridge
    command:
      - start-dev

networks:
  bridge:

volumes:
  db:
